/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.manianis.frames;

import javax.swing.*;

/**
 *
 * @author manianis
 * @param <T>
 */
public class BaseDialog<T extends Object> extends JDialog {

    private int dialogResult;
    protected T data;

    /** Creates new form BaseDialog */
    public BaseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dialogResult = JOptionPane.CANCEL_OPTION;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
        dataToGui();
    }

    public boolean isValidData() { return true;}

    public void dataToGui() {}

    public void guiToData() {}

    public void acceptChanges() {
        if (isValidData()) {
            dialogResult = JOptionPane.OK_OPTION;
            guiToData();
            setVisible(false);
            dispose();
        }
    }

    public void rejectChanges() {
        dialogResult = JOptionPane.CANCEL_OPTION;
        setVisible(false);
        dispose();
    }

    public int getDialogResult() {
        return dialogResult;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
