/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.manianis.frames;

import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import tn.manianis.editors.TableCellEditorBase;
import tn.manianis.entities.EpreuvesCollection;
import tn.manianis.renderers.DefaultCellRenderer;
import tn.manianis.renderers.HeaderRenderer;
import tn.manianis.tablemodels.CoefficientsTableModel;
import tn.manianis.utils.ComponentUtils;

/**
 *
 * @author manianis
 */
public class EditCoefficientsFrame extends BaseDialog<EpreuvesCollection> {
    
    private CoefficientsTableModel tableModel;

    /** Creates new form EditCoefficientsFrame */
    public EditCoefficientsFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ComponentUtils.setOrientationRTL(rootPane);
    }
    
    private void initTable() {
        JTableHeader header = coefTable.getTableHeader();
        header.setDefaultRenderer(new HeaderRenderer(coefTable));
        setTableColumnsWidths();
    }
    
    private void setTableColumnsWidths() {
        int colCount = coefTable.getColumnCount();
        coefTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        coefTable.getColumnModel().getColumn(1).setPreferredWidth(80);
        coefTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        for (int i = 0; i < colCount; i++) {
            TableColumn tc = coefTable.getColumnModel().getColumn(i);
            tc.setCellRenderer(new DefaultCellRenderer());
            tc.setCellEditor(new TableCellEditorBase());
        }
    }

    @Override
    public void setData(EpreuvesCollection data) {
        this.data = data;
        tableModel = new CoefficientsTableModel(data);
        coefTable.setModel(tableModel);
        initTable();
        dataToGui();
    }
    
    @Override
    public boolean isValidData() {
        return super.isValidData();
    }

    @Override
    public void dataToGui() {
        
    }

    @Override
    public void guiToData() {

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomPanel = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(32767, 32767));
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        coefTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تغيير الضوارب");
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        bottomPanel.setLayout(new javax.swing.BoxLayout(bottomPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnReset.setText("الضوارب المعتمدة...");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        bottomPanel.add(btnReset);
        bottomPanel.add(filler1);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publicationnotes_2/images/valider.png"))); // NOI18N
        btnOk.setText("موافقة");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        bottomPanel.add(btnOk);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publicationnotes_2/images/annuler.png"))); // NOI18N
        btnCancel.setText("إلغاء");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        bottomPanel.add(btnCancel);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        coefTable.setAutoCreateRowSorter(true);
        coefTable.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        coefTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        coefTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(coefTable);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(null);

        setSize(new java.awt.Dimension(456, 231));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        acceptChanges();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        rejectChanges();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tableModel.rejectChanges();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.JTable coefTable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
