/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.manianis.frames;

import tn.manianis.entities.Note;
import tn.manianis.entities.Observation;
import tn.manianis.utils.ComponentUtils;

import javax.swing.*;

/**
 * @author manianis
 */
public class EditObservationFrame extends BaseDialog<Observation> {

    private EditModeType editModeType;

    /**
     * Creates new form EditObservationFrame
     */
    public EditObservationFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ComponentUtils.setOrientationRTL(this.rootPane);
        setLocationRelativeTo(parent);
    }

    public void setEditModeType(EditModeType editModeType) {
        this.editModeType = editModeType;
        String title = "";
        if (editModeType == EditModeType.NEW) {
            title = "إضافة ملاحظة";
        } else if (editModeType == EditModeType.EDIT) {
            title = "تغيير ملاحظة";
        }
        setTitle(title);
        txtNote.setEnabled(editModeType == EditModeType.NEW);
    }

    public EditModeType getEditModeType() {
        return editModeType;
    }

    @Override
    public boolean isValidData() {
        StringBuilder sb = new StringBuilder();
        if (txtObservation.getText().length() == 0) {
            sb.append("الرجاء كتابة ملاحظة\n");
        }
        try {
            Double dbl = Double.parseDouble(txtNote.getText());
            if (!Note.isValid(dbl)) {
                sb.append("العدد يتراوح بين 0 و 20\n");
            }
        } catch (NumberFormatException e) {
            sb.append("الرجاء كتابة عدد\n");
        }
        if (!sb.isEmpty()) {
            JOptionPane.showMessageDialog(null, sb.toString(), getTitle(), JOptionPane.INFORMATION_MESSAGE);
        }
        return sb.isEmpty();
    }

    @Override
    public void dataToGui() {
        txtObservation.setText(data.getObservation());
        txtNote.setText(data.getNote().toString());
    }

    @Override
    public void guiToData() {
        data.setObservation(txtObservation.getText());
        data.setNote(Double.parseDouble(txtNote.getText()));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNote = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        lblObservation = new javax.swing.JLabel();
        txtObservation = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تغيير الملاحظة");
        setModal(true);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[]{60, 60, 60, 60};
        layout.columnWeights = new double[]{1.0, 1.0, 1.0, 1.0};
        layout.rowWeights = new double[]{1.0, 1.0, 1.0};
        getContentPane().setLayout(layout);

        lblNote.setText("العدد");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblNote, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtNote, gridBagConstraints);

        lblObservation.setText("الملاحظة");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblObservation, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtObservation, gridBagConstraints);

        btnOk.setText("موافقة");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(btnOk, gridBagConstraints);

        btnCancel.setText("إلغاء");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(btnCancel, gridBagConstraints);

        setBounds(0, 0, 410, 131);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        acceptChanges();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        rejectChanges();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblObservation;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtObservation;
    // End of variables declaration//GEN-END:variables

}
