/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.manianis.frames;

import tn.manianis.editors.TableCellEditorBase;
import tn.manianis.entities.Observation;
import tn.manianis.entities.ObservationCollection;
import tn.manianis.renderers.DefaultCellRenderer;
import tn.manianis.renderers.HeaderRenderer;
import tn.manianis.tablemodels.ObservationsTableModel;
import tn.manianis.utils.ComponentUtils;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import java.awt.*;

/**
 * @author manianis
 */
public class ObservationsFrame extends JInternalFrame {

    private ObservationCollection observations;
    private ObservationsTableModel tableModel;
    private int dialogResult;

    /**
     * Creates new form ObservationsFrame
     */
    public ObservationsFrame(JFrame parent) {
        super("", true, true, true, false);
        observations = MainFrame.getObservations().cloneArray();
        tableModel = new ObservationsTableModel(observations);
        initComponents();
        ComponentUtils.setOrientationRTL(this.rootPane);
        initTable();
        refreshButtons();
    }

    /**
     * Init table
     */
    private void initTable() {
        JTableHeader header = obsTable.getTableHeader();
        header.setDefaultRenderer(new HeaderRenderer(obsTable));
        setTableColumnsWidths();
    }

    /**
     * Set table columns widths and renderers
     */
    private void setTableColumnsWidths() {
        int colCount = obsTable.getColumnCount();
        obsTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        obsTable.getColumnModel().getColumn(1).setPreferredWidth(80);
        obsTable.getColumnModel().getColumn(2).setPreferredWidth(240);
        for (int i = 0; i < colCount; i++) {
            TableColumn tc = obsTable.getColumnModel().getColumn(i);
            tc.setCellRenderer(new DefaultCellRenderer());
            tc.setCellEditor(new TableCellEditorBase());
        }
        obsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                if (!listSelectionEvent.getValueIsAdjusting()) {
                    refreshButtons();
                }
            }
        });
        tableModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent tableModelEvent) {
                refreshButtons();
            }
        });
    }

    private void refreshButtons() {
        int selectedRows = obsTable.getSelectedRowCount();
        btnEdit.setEnabled(selectedRows == 1);
        btnRemove.setEnabled(selectedRows > 0);
        btnCancel.setEnabled(tableModel.isDirty());
    }

    public ObservationCollection getTableModelData() {
        return tableModel.getCollection();
    }

    public int getDialogResult() {
        return dialogResult;
    }

    public boolean isDirty(){
        return tableModel.isDirty();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnReload = new javax.swing.JButton();
        middlePanel = new javax.swing.JPanel();
        scrollPane1 = new javax.swing.JScrollPane();
        obsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("الملاحظات");

        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnAdd.setText("إضافة");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        topPanel.add(btnAdd);

        btnEdit.setText("تغيير");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        topPanel.add(btnEdit);

        btnRemove.setText("فسخ");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        topPanel.add(btnRemove);
        topPanel.add(filler1);

        btnCancel.setText("تراجع");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        topPanel.add(btnCancel);
        topPanel.add(filler2);

        btnReload.setText("الملاحظات القياسية");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        topPanel.add(btnReload);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        middlePanel.setLayout(new java.awt.BorderLayout());

        obsTable.setAutoCreateRowSorter(true);
        obsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        obsTable.setModel(tableModel);
        obsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        obsTable.setRowHeight(24);
        obsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        obsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        obsTable.setShowGrid(true);
        scrollPane1.setViewportView(obsTable);

        middlePanel.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(middlePanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 542, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        if (JOptionPane.showConfirmDialog(this,
                "هل تريد إستعادة الملاحظات القياسية وفسخ كافة التغييرات؟",
                getTitle(),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            tableModel.resetData();
        }
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        EditObservationFrame editObservation = new EditObservationFrame(null, true);
        editObservation.setEditModeType(EditModeType.NEW);
        editObservation.setData(new Observation());
        editObservation.setVisible(true);
        if (editObservation.getDialogResult() == JOptionPane.OK_OPTION) {
            tableModel.addRow(editObservation.getData());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        ListSelectionModel selectionModel = obsTable.getSelectionModel();
        int start = selectionModel.getMinSelectionIndex();
        int end = selectionModel.getMaxSelectionIndex();
        if (start == -1 || end == -1) {
            return;
        }
        if (JOptionPane.showConfirmDialog(
                this,
                "هل تريد فعلا حذف هذه الملاحظات ؟",
                this.getTitle(),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }
        for (int i = end; i >= start; i--) {
            int index = obsTable.getRowSorter().convertRowIndexToModel(i);
            tableModel.removeRows(index, index);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        tableModel.rejectChanges();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = obsTable.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        Observation observation = (Observation) tableModel.getRowAt(obsTable.getRowSorter().convertRowIndexToModel(selectedRow));
        EditObservationFrame editObservation = new EditObservationFrame(null, true);
        editObservation.setEditModeType(EditModeType.EDIT);
        editObservation.setData(new Observation(observation));
        editObservation.setVisible(true);
        if (editObservation.getDialogResult() == JOptionPane.OK_OPTION) {
            tableModel.addRow(editObservation.getData());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnRemove;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JTable obsTable;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
